name: Integration Workflow

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: [\d+.\d+.\d+]

jobs:
  lint:
    name: Linting - Hadolint for all changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile

  build:
    name: Build - DockerHub for all changes pushed
    needs: lint
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_HUB_REPOSITORY }}
      MESSAGE_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK_URL }}
      USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
    steps:
      - name: Set staging build
        if: startsWith(github.ref, 'refs/heads/main')
        run: echo "IMAGE_VERSION=latest" >> $GITHUB_ENV

      - name: Set production build
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "IMAGE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Send build started message to MS Teams
        uses: dhollerbach/github-action-send-message-to-ms-teams@1.0.10
        with:
          webhook: ${{ env.MESSAGE_WEBHOOK }}
          message: 'Started building <b><a href=${{github.event.repository.html_url}}>${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}</a></b>'

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          # Key is named differently to avoid collision
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.USER }}
          password: ${{ env.PASSWORD }}

      - uses: actions/checkout@v2

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          # Note the mode=max here
          # More: https://github.com/moby/buildkit#--export-cache-options
          # And: https://github.com/docker/buildx#--cache-tonametypetypekeyvalue
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Send build finished message to MS Teams
        uses: dhollerbach/github-action-send-message-to-ms-teams@1.0.10
        with:
          webhook: ${{ env.MESSAGE_WEBHOOK }}
          message: 'Finished building <b><a href=${{github.event.repository.html_url}}>${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}</a></b>'

      - name: Send build failed message to MS Teams
        if: ${{ failure() }}
        uses: dhollerbach/github-action-send-message-to-ms-teams@1.0.10
        with:
          webhook: ${{ env.MESSAGE_WEBHOOK }}
          message: '<b><a href=${{github.event.repository.html_url}}>${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}</a></b> *HAS FAILED!* Panic?'
