name: Integration Workflow

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: [\d+.\d+.\d+]

jobs:
  lint-dockerfile:
    name: Linting Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Dockerfile
          sparse-checkout-cone-mode: false
      - name: Running Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  lint-docker-compose:
    name: Linting Docker Compose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            docker-compose.yml
          sparse-checkout-cone-mode: false
      - name: Linting docker-compose with config
        run: exit ${docker compose config}

  build:
    name: Build and publish
    needs: [lint-dockerfile, lint-docker-compose]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    env:
      ACTION_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      IMAGE_VERSION: latest
    steps:
      - name: Configure production build
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "IMAGE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Send build started message to MS Teams
        uses: dhollerbach/github-action-send-message-to-ms-teams@v3
        with:
          webhook: ${{ secrets.TEAMS_WEBHOOK_URL }}
          message: |
            'Started building <b><a href=${{ env.ACTION_URL }}>${{ github.repository }}:${{ env.IMAGE_VERSION }}</a></b>'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: actions/checkout@v4

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ vars.DOCKER_HUB_REPOSITORY }}:${{ env.IMAGE_VERSION }}

      - name: Send build finished message to MS Teams
        uses: dhollerbach/github-action-send-message-to-ms-teams@v3
        with:
          webhook: ${{ secrets.TEAMS_WEBHOOK_URL }}
          message: "Finished building <b><a href=${{ env.ACTION_URL }}>${{ github.repository }}:${{ env.IMAGE_VERSION }}</a></b>"

      - name: Send build failed message to MS Teams
        if: ${{ failure() }}
        uses: dhollerbach/github-action-send-message-to-ms-teams@v3
        with:
          webhook: ${{ secrets.TEAMS_WEBHOOK_URL }}
          message: "<b><a href=${{ env.ACTION_URL }}>${{ github.repository }}:${{ env.IMAGE_VERSION }}</a></b> *HAS FAILED!* Panic?"
